List<String> lincolnQuotes = [
  "My concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right",
  "There are no bad pictures; that's just how your face looks sometimes.",
  "Those who look for the bad in people will surely find it.",
  "I don't like that man. I must get to know him better.",
  "Tact: the ability to describe others as they see themselves.",
  "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.",
  "No man has a good enough memory to be a successful liar",
  "You can tell the greatness of a man by what makes him angry",
  "The Lord prefers common-looking people. That is why he made so many of them.",
  "It is difficult to make a man miserable while he feels worthy of himself and claims kindred to the great God who made him.",
  "When I get ready to talk to people, I spend two thirds of the time thinking what they want to hear and one third thinking about what I want to say.",
  "We should be too big to take offense and too noble to give it.",
  "The things I want to know are in books; my best friend is the man who'll get me a book I ain't read",
  "I desire so to conduct the affairs of this administration that if at the end... I have lost every other friend on earth, I shall at least have one friend left, and that friend shall be down inside of me.",
  "Surely God would not have created such a being as man, with an ability to grasp the infinite, to exist only for a day! No, no, man was made for immortality",
  "The shepherd drives the wolf from the sheep's throat, for which the sheep thanks the shepherd as his liberator, while the wolf denounces him for the same act as the destroyer of liberty. Plainly, the sheep and the wolf are not agreed upon a definition of liberty.",
  "Don't worry when you are not recognized, but strive to be worthy of recognition",
  "I am a slow walker, but I never walk back",
  "Be sure you put your feet in the right place, then stand firm",
  "How many legs does a dog have if you call his tail a leg? Four. Saying that a tail is a leg doesn't make it a leg",
  "That some achieve great success, is proof to all that others can achieve it as well.",
  "You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time."
];
