// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kYhVsJynritzcYqjaTfJUv4YXWXggjo',
    appId: '1:529470364549:web:bf3690df6fc4f9627f82ec',
    messagingSenderId: '529470364549',
    projectId: 'realised-souls',
    authDomain: 'realised-souls.firebaseapp.com',
    databaseURL: 'https://realised-souls-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'realised-souls.appspot.com',
    measurementId: 'G-EJKDZZQTB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7P23OK_U115Mnx0l7h7txilkUaOIa2U',
    appId: '1:529470364549:android:9a71fc72323e0a657f82ec',
    messagingSenderId: '529470364549',
    projectId: 'realised-souls',
    databaseURL: 'https://realised-souls-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'realised-souls.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0Mrqizi5vF6vk48z5lNTgU4PAxJPTk0',
    appId: '1:529470364549:ios:581b69ea469b2ce67f82ec',
    messagingSenderId: '529470364549',
    projectId: 'realised-souls',
    databaseURL: 'https://realised-souls-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'realised-souls.appspot.com',
    iosClientId: '529470364549-cbfn7a6l0s0hvsm8butjg84l09r52bl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.realisedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0Mrqizi5vF6vk48z5lNTgU4PAxJPTk0',
    appId: '1:529470364549:ios:0f9442ed1de5fec97f82ec',
    messagingSenderId: '529470364549',
    projectId: 'realised-souls',
    databaseURL: 'https://realised-souls-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'realised-souls.appspot.com',
    iosClientId: '529470364549-7gck8716q4kk06h9frg8pnc92lb90933.apps.googleusercontent.com',
    iosBundleId: 'com.example.realisedApp.RunnerTests',
  );
}
